### ISSUE TITLE
Create dark theme styles & toggle

### ISSUE THREAD

**Issue by amychurchwell** [amychurchwell/amychurchwell.com#3]
Utilize custom css properties -- https://alxgbsn.co.uk/2019/02/08/blog-theming-css-variables/

**Comment by amychurchwell** [comment]
Toggle inspiration:

![image](https://user-images.githubusercontent.com/30483988/54328037-a5910b00-45c9-11e9-925f-9ae5344e724e.png)

**Comment by amychurchwell** [comment]
https://archive.org/details/winampskin_wasakura
![Screen Shot 2019-03-18 at 12 41 04 PM](https://user-images.githubusercontent.com/30483988/54558504-29a51300-497b-11e9-9288-225176faa9fe.png)
_better contrast_

**Comment by amychurchwell** [comment]
**TO-DO**: 
- [ ] Theme toggle & local storage functional (JS) but needs tidying.
-  [ ] Radio buttons need style.
- [ ] Add `prefers-color-scheme` default.

**Comment by amychurchwell** [comment]
completed in previous website design, may or may not do this for current iteration. /shrug
